name: turna_tv
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  first_time_screen: ^1.0.3
  login_screen: ^0.6.0
  intro_views_flutter: "^2.4.0"
  loading_animations: "^2.1.0"
  flutter_bloc: ^4.0.0
  carousel_slider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - ./lib/presentation/assets/
